version: '3.1'

services:
  wordpress:
    container_name: ${SITE_NAME}-wp
    image: wordpress
    restart: unless-stopped
    env_file:
      - path: .env
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${SITE_NAME}-db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html

  db:
    container_name: ${SITE_NAME}-db
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    env_file:
      - path: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  cli:
    container_name: ${SITE_NAME}-cli
    depends_on:
      - wordpress
      - db
    image: bdelphin/wp_cli_mariadb-connector
    restart: unless-stopped
    user: 1000:1000
    command: tail -f /dev/null # to keep container running !
    volumes:
      - ./wordpress:/var/www/html
      - ./export:/var/www/export # folder to store DB exports
    env_file:
      - path: .env
    environment:
      WORDPRESS_DB_HOST: ${SITE_NAME}-db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

volumes:
  wordpress:
  db: